trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: DownloadSecureFile@1
    name: testSync
    displayName: 'Download the Deploy Key'
    inputs:
      secureFile: 'test-sync'

  - script: |
      mkdir -p ~/.ssh
      cp $(testSync.secureFilePath) ~/.ssh/id_rsa 
      cat ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan github.com >> ~/.ssh/known_hosts
    displayName: 'Setup SSH for GitHub'

  - script: |
      echo "Setting up the user"
      git branch
      git status
      git config --global user.name "Azure DevOps"
      git config --global user.email "bit-midar-dev@openwt.com"
      git remote add github git@github.com:m-gl/test-sync-target.git
      git remote -v
      echo "Pushing"
      git push github HEAD:main
    displayName: 'Sync to GitHub'